Task_1_1_2
RostyanYandexLyceumCheeeeck/OOP pull request #2
Opened 2024-09-21 23:02 UTC by RostyanYandexLyceumCheeeeck

pr 1_1_2!

2024-09-22 14:21 UTC, Sharapov-Maksim requested changes
Для ревью к жёсткому дедлайну обязательно прохождение checkstyle. Если есть вопросы, задавайте

2024-09-22 15:05 UTC, RostyanYandexLyceumCheeeeck commented
запрос итерации ревью)

2024-09-22 15:50 UTC, RostyanYandexLyceumCheeeeck commented
запрос очередной итерации ревью, checkstyle прошёл)

2024-09-22 16:06 UTC, Sharapov-Maksim requested changes

2024-09-22 16:06 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +                String str1 = (resultRound > 0 ? messageWinRoundPlayer0 : messageWinRoundDealer0);
Придумайте переменной название получше

2024-09-22 16:06 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/Card.java
> +    private final int value;
Под имя `value` больше подходит стоимость карты, в данном случае для поля лучше было указать имя `index`

2024-09-22 16:06 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/Card.java
> +            throw new Exception("Card value cannot be negative");
Уже исключения кидаете, неплохо)
Расскажите тогда, что такое исключения и почему вы решили тут им воспользоваться?

2024-09-22 16:06 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/Player.java
> +    private void setHand() {
Ни название метода, ни javadoc, не помогают понять, что этот метод делает, надо поправить

2024-09-22 16:06 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/Card.java
> +public class Card {
Сейчас карта представляется ввиде порядкового номера (`value`), по которому динамически вычисляются её стоимость и масть. Предлагаю поменять подход, и добавить полей, заполняемых стоимостью и строковым представлением на этапе создания объекта, в конструкторе. Так вся нужная информация будет всегда храниться в полях объекта и остальные методы станут проще

2024-09-22 16:06 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +    private int startRound(Scanner console, int number) throws Exception {
Метод `startRound` у вас проводит весь раунд и выдаёт победителя -- нелогичное название

2024-09-22 16:06 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +        int winDealer = -1;
Давайте для результата заведём `enum` с вариантами исхода раунда. А то такой способ задания результата не очень-то удобен/читаем

2024-09-22 16:06 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +    interface MyInterface {
Расскажите, что такое интерфейс и почему вы использовали его, чем он вам тут помог?

2024-09-22 16:06 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +    interface MyInterface {
Название интерфейса неудачное, надо бы что-нибудь более осмысленное

2024-09-22 16:06 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +        MyInterface copyPaste = (human, prefix, index1) -> {
`copyPaste`?

2024-09-22 16:06 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +            dealer.addCard(this.cards.get(++index));
Инкрементировать индуктивную переменную в двух местах - очень плохо читается.
Лучше сделать
```
for (;; index+= 2) {
... index ...
... index + 1 ...
}
```

2024-09-22 16:06 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +        this.cards.get(indexCloseCardDealer).faceUp = false;
Глядите что получается:

1. Берём карту из колоды, но карта остаётся в колоде (`this.cards.get()`)
2. Делаем `dealer.addCard`, передаём карту дилеру
3. Снова ищем в колоде карту с захардкоженым индексом и меняем её состояние

При этом информация о картах на руках игроков никак не используется.

Было бы логичнее удалять карту из колоды при передаче её игроку, ведь имено так оно и происходит в игре, а ваша объектная модель должна быть отражением сущностей игры. А если надо что-то сделать с картой игрока, то запросить у него эту карту, и у самой карты позвать нужный метод, например `open()` или `close()`

2024-09-23 04:02 UTC, Sharapov-Maksim requested changes
Ещё немного правок

2024-09-23 04:02 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackjack/Card.java
> +    public Card(int value, boolean isFaceUp)  throws Exception {
В тестах очень хорошо видно, что ваш подход к конструкции `Card` не удобен. Давайте сделаем так, чтобы конструктор принимал сразу нужную информацию, а не искал её во вспомогательных массивах по передаваемому индексу.

2024-09-23 04:02 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackjack/BlackJack.java
> +    private void setCards() throws Exception {
Установить модификатор доступа `protected` и протестировать

2024-09-23 04:02 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackjack/BlackJack.java
> +    private int startRound(Scanner console, int number) throws Exception {
`protected` и протестировать

Чтобы симулировать ввод пользователя в качестве сканера можно передать что-нибудь такое: `new Scanner("0\n")` - в таком случае наш симулятивный пользователь будет всегда останавливаться и не брать карты, стоит сделать и другие сценарии

2024-09-23 08:04 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +                String str1 = (resultRound > 0 ? messageWinRoundPlayer0 : messageWinRoundDealer0);
fix

2024-09-23 08:04 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/Card.java
> +    private final int value;
fix

2024-09-23 08:04 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/Player.java
> +    private void setHand() {
fix

2024-09-23 08:04 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +    private int startRound(Scanner console, int number) throws Exception {
fix

2024-09-23 08:05 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +            dealer.addCard(this.cards.get(++index));
fix

2024-09-23 08:18 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/Card.java
> +            throw new Exception("Card value cannot be negative");
Исключения -- это непредвиденные ситуации при выполнении программы, которые ломают логику исполнения программы. 

воспользоваться решил, т.к. по значению `value` у меня многое что вычисляется, включая выисления индексов для обращения в статические массивы `suits` и `ranks`. если значение `value` будет отрицательным, ==> индекс обращения в массив `suits` будет отрицательным, ==> полетит неявное исключение(обращение по отрицательному индексу). Да и вся остальная логика других методов будет неправильной, если `value` будет отрицательным. Поэтому я выкидываю собственное исключение, предупреждающее, что `value` должно быть неотрицательным числом.

2024-09-23 08:22 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/Card.java
> +public class Card {
ну, тогда будет тратиться слишком много памяти в программе(дорого хранить строковое представление для каждой карты, тем более, если пользователь введёт ооочень большое кол-во используемых колод). именно поэтому я и вынес это в статические массивы. а методы и так простые, предельно понятные.

да и всё равно, если даже и хранить строковое представление, оно всё равно может измениться(для туза, например. где ценность поменять надо будет в скобках).

2024-09-23 08:23 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +        int winDealer = -1;
не понял, что вы имеете ввиду)

2024-09-23 08:31 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +    interface MyInterface {
вообще, интерфейсы обычно делают для классов. тобеж интерфейсы описывают, какие методы точно будут(но не саму логику исполнения метода), а класс как раз-таки реализует логику метода.

использовал я его для одной единственной цели -- избавиться от копипастинга(именно поэтому не заморачивался с неймингом как самого интерфейса, так и его экземпляра). копипаст возникал, когда выводится "Вы вытянули карту..." и "Дилер вытянул карту...". Вот и решил таким способом избавиться от копипаста.


Да, понимаю, что это по факту "костыль", но я попросту не мог смотреть на явный копипаст, а с джавой я работаю впервые, и такой "способ убрать копипаст" я нашёл на stackoverflow. если надо, могу вернуть копипаст, убрав интерфейс.

2024-09-23 08:32 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +    interface MyInterface {
ответил в комментарии выше ↑

2024-09-23 08:32 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +        MyInterface copyPaste = (human, prefix, index1) -> {
ответил на 2 комментария выше ↑↑

2024-09-23 08:43 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +        this.cards.get(indexCloseCardDealer).faceUp = false;
> "то запросить у него эту карту"
А если у игрока(имеется ввиду экземпляр класса `Player`) несколько одинаковых карт в руке(в силу возможности использования нескольких колод), тогда какую из них нужно получить? Тогда, при обращении к определённой карте нужно будет изначально знать ссылку на неё(или какие-то отличительные свойства??). То есть, по факту, ты изначально должен будешь знать ссылки на все карты(чтобы была возможность обратиться к любой карте, находящейся у кого-то в руке). 

> "Снова ищем в колоде карту с захардкоженым индексом и меняем её состояние"
ну, у нас же правила игры фиксированы? то есть, мы по правилам игры написали программу. Да, захардкожено немного, но  это поясняется тем, что правила неизменны(ибо для других правил другая игра, получается).

2024-09-23 08:51 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackjack/Card.java
> +    public Card(int value, boolean isFaceUp)  throws Exception {
> "Давайте сделаем так, чтобы конструктор принимал сразу нужную информацию"
не понимаю, какую информацию он должен принимать? описание_карты/её_ценность/открыта_или_закрыта? тогда для каждой карты надо будет проверять, что ценность совпадает с описанием карты(тобеж, чтобы не было такого, что ввели "Туз червей", а стоимость 7). это, получается, надо хеш-таблицу создавать или что-то подобное. Как по мне, это слишком много власти для пользователя(имеется ввиду того, кто будет использовать данный класс), много возможностей словить неявное исключение. Как по мне, проще, например, в javadoc-e написать, что к чему(имеется ввиду какое значение должно быть, как задать карту через число), и всё. Если пользователь класса не собирается следовать условиям -- это же уже его проблемы))

2024-09-23 10:16 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackjack/Card.java
> +    public Card(int value, boolean isFaceUp)  throws Exception {
> тогда для каждой карты надо будет проверять, что ценность совпадает с описанием карты(тобеж, чтобы не было такого, что ввели "Туз червей", а стоимость 7). это, получается, надо хеш-таблицу создавать или что-то подобное.

Хорошо, что вы думаете про ограничение возможностей для использования, это можно сделать без хэш таблиц. 

В задаче **базовая** стоимость карты определяется однозначно по её "картинке"/"числу". Можно сделать `enum`, перечисление всех допустимых значений карт.

Что-нибудь вроде:
```
public enum Rank {
    TWO(2, "Двойка"),
    ...
    TEN(10, "Десятка"),
    JACK(10, "Валет"),
    QUEEN(10, "Дама"),
    KING(10, "Король"),
    ACE(11, "Туз");

    final int points;
    final String name;

    Rank(int points, String name) {
        this.points = points;
        this.name = name;
    }
```

Тогда в коде можно будет ссылаться на уникальные объекты, хранящие в себе всю информацию (напр., Rank.TEN).
Так же можно задать и масти карт, там проще.

Чтобы колоды было легче заполнять, по перечислениям (`enum`) можно итерироваться

2024-12-24 03:23 UTC, RostyanYandexLyceumCheeeeck commented
запрос итерации ревью)

2024-12-24 03:25 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackjack/BlackJack.java
> +    private int startRound(Scanner console, int number) throws Exception {
fixed

2024-12-24 03:25 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackjack/BlackJack.java
> +    private void setCards() throws Exception {
fixed

2024-12-24 03:25 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackjack/Card.java
> +    public Card(int value, boolean isFaceUp)  throws Exception {
fixed

2024-12-24 03:25 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_2/src/main/java/ru/nsu/syspro/zagitov/blackJack/BlackJack.java
> +        this.cards.get(indexCloseCardDealer).faceUp = false;
fixed

2025-02-03 04:15 UTC, merged