Task_1_1_3
RostyanYandexLyceumCheeeeck/OOP pull request #3
Opened 2024-10-01 06:54 UTC by RostyanYandexLyceumCheeeeck

YA GHOUL!

2024-10-02 01:40 UTC, Sharapov-Maksim requested changes
Доделывайте, мягкий дедлайн зачтён

2024-10-02 01:40 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operations_with_equations/Expression.java
> +    }
Надо будет убрать реализацию у метода, как и у `derivative`. Это же абстрактный класс, в нём не обязательны реализации всех методов

2024-10-02 01:40 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operations_with_equations/Expression.java
> +    protected int __eval__(ArrayList<String> names, ArrayList<Integer> values) {
В Java не приняты имена с `_`. Если хотите сделать метод приватным, то делаете его `private` с обычным названием в стиле `lowerCamelCase`

2024-10-07 19:23 UTC, RostyanYandexLyceumCheeeeck commented
review please!

2024-10-08 10:46 UTC, Sharapov-Maksim requested changes

2024-10-08 10:46 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +            }
Нужно кидать не общее исключение, а более конкретный вид, например, `IllegalArgumentException` или собственное сделать. Тип исключения должен помогать описать его причину

2024-10-08 10:46 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +    }
Логично сделать метод `static`, он же как раз призван создавать объект, а не вызываться от объекта

2024-10-08 10:46 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +    public Expression convertStringToExpression(String expression) {
Протестировать

2024-10-08 10:46 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +public abstract class Expression {
Сделайте ещё метод `print`, который требуется по второму пункту задачи

2024-10-08 10:46 UTC, Sharapov-Maksim commented on Task_1_1_3/src/test/java/ru/nsu/syspro/zagitov/operationswithequations/TestVariable.java
> +    }
Можете объяснить, зачем вам эти обёрточные классы во всех тестах? Почему нельзя просто `Variable` и остальные  использовать?

2024-10-08 10:46 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Parser.java
> +    protected static ArrayList<String> stringExpressionToArrayRpn(String expression) {
Я правильно понимаю, что вы планируете сдавать задачу с выполненным первым доп. условием?

2024-10-08 17:49 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Parser.java
> +    protected static ArrayList<String> stringExpressionToArrayRpn(String expression) {
Да
и планирую выполнить второе доп.условие

2024-10-08 18:12 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/test/java/ru/nsu/syspro/zagitov/operationswithequations/TestVariable.java
> +    }
Да, я писал код ночью, и чёт подумал, что если я тестирую `protected` метод, то надо создать новый класс, унаследовав его от нужного, и создать `public` метод, который будет вызывать `protected` метод(по факту, просто обёртка). 
то есть изначчально у меня код был такой:
 ```
     static class TestProtectedEvalVariable extends Variable {
       public TestProtectedEvalVariable(String value) {
            super(value);
        }
        public int testProtectedEval(ArrayList<String> names, ArrayList<Integer> values) {
            return protectedEval(names, values);
        }
    }
    ```
    но потом убрал этот метод, а класс забыл убрать
    
    ну то есть я не знал, что в юнит тестах можно без обёрточного класса протестировать `protected` метод

2024-10-08 19:05 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +public abstract class Expression {
fix

2024-10-08 19:05 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +    }
fix

2024-10-08 19:05 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +    public Expression convertStringToExpression(String expression) {
fix

2024-10-08 19:05 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +            }
fix

2024-10-08 19:59 UTC, RostyanYandexLyceumCheeeeck commented
review please! 2.0

2024-10-09 05:05 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Parser.java
> +    protected static ArrayList<String> stringExpressionToArrayRpn(String expression) {
Все доп. условия надо сдавать вместе с основной задачей. Сейчас у вас оно выполнено?

2024-10-09 05:15 UTC, Sharapov-Maksim requested changes
Жду выполнения доп. задания, исправления замечаний checkstyle

2024-10-09 05:15 UTC, Sharapov-Maksim commented on Task_1_1_3/src/test/java/ru/nsu/syspro/zagitov/operationswithequations/TestAdd.java
> +    void testConvertStringToExpression1() {
Почему тесты раскиданы по `TestAdd`, `TestDiv`? Давайте их в отдельный класс вынесем, они не принадлежат к конкретным операциям

2024-10-09 05:15 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +    abstract public void print();
У вас все реализации, кажется, совпадают. Чтобы не дублировать код, стоит эту реализацию добавить сюда, тогда в наследниках она станет не нужна

2024-10-09 05:15 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +    static public Expression convertStringToExpression(String expression) {
Добавить тесты на выполненное доп. задание №1, где отсутствуют скобки

2024-12-10 14:19 UTC, RostyanYandexLyceumCheeeeck commented
Запрос итерации ревью)

2024-12-10 17:24 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +    abstract public void print();
fix

2024-12-10 17:24 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/test/java/ru/nsu/syspro/zagitov/operationswithequations/TestAdd.java
> +    void testConvertStringToExpression1() {
fixed

2024-12-10 17:25 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +    static public Expression convertStringToExpression(String expression) {
fix

2024-12-12 17:37 UTC, Sharapov-Maksim requested changes

2024-12-12 17:37 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Add.java
> +        if (result.left.getClass() == Number.class && result.right.getClass() == Number.class) {
`result.left instanceof Number` и аналогично везде, так вы сможете обработать и наследников `Number`

2024-12-12 17:37 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +    protected abstract int protectedEval(ArrayList<String> names, ArrayList<Integer> values);
Лучше здесь принимать `Map<String, Integer>`, вы же в действительности принимаете отображение из имён в строки

2024-12-12 17:37 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +        );
Вынести в static переменную, чтобы компиляция происходила единожды

2024-12-12 17:37 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Add.java
> +            return new Number(result.left.eval("x = 0") + result.right.eval("x = 0"));
Зачем `"x = 0"`? Нужно сделать возможность задания пустого означивания

2024-12-12 17:37 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Variable.java
> +        throw new ArithmeticException("Arithmetic Error! \"" + value + "\" not found!");
Это не арифметическая ошибка, измените тип исключения и перефразируйте сообщение

2024-12-12 17:37 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Variable.java
> +    String value;
`name`?

2024-12-12 17:37 UTC, Sharapov-Maksim commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Sub.java
> +        if (result.left.toString().equals(result.right.toString())) {
Добавьте `abstract equals()` в `Expression`, и реализуйте. Вместо использования `toString().equals()` пользуйтесь `equals()`

2024-12-12 17:37 UTC, Sharapov-Maksim commented on Task_1_1_3/src/test/java/ru/nsu/syspro/zagitov/operationswithequations/TestExpression.java
> +        Assertions.assertEquals("32", simplifyExpression.toString());
Здесь тоже пользуйтесь сделанным `equals()`

2024-12-14 11:40 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Variable.java
> +    String value;
fixed

2024-12-14 11:40 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Variable.java
> +        throw new ArithmeticException("Arithmetic Error! \"" + value + "\" not found!");
fixed

2024-12-14 11:40 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Add.java
> +            return new Number(result.left.eval("x = 0") + result.right.eval("x = 0"));
fixed

2024-12-14 11:40 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +        );
fixed

2024-12-14 11:41 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Expression.java
> +    protected abstract int protectedEval(ArrayList<String> names, ArrayList<Integer> values);
fixed

2024-12-14 11:41 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_1_3/src/main/java/ru/nsu/syspro/zagitov/operationswithequations/Add.java
> +        if (result.left.getClass() == Number.class && result.right.getClass() == Number.class) {
fixed

2024-12-14 11:41 UTC, RostyanYandexLyceumCheeeeck commented
Review, please!)

2024-12-14 17:43 UTC, Sharapov-Maksim approved these changes
Задание зачтено

2025-02-03 04:15 UTC, merged