Task_1_3_1
RostyanYandexLyceumCheeeeck/OOP pull request #4
Opened 2024-11-11 23:38 UTC by RostyanYandexLyceumCheeeeck

YEP!

2024-11-12 07:11 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн зачтён

2024-11-12 07:11 UTC, Sharapov-Maksim commented on Task_1_3_1/src/main/java/ru/nsu/syspro/zagitov/find/Main.java
> +}
Лишний класс надо либо убрать, либо наполнить использованием `FindSubstring`

2024-11-12 07:11 UTC, Sharapov-Maksim commented on Task_1_3_1/src/test/java/ru/nsu/syspro/zagitov/find/TestFindSubstring.java
> +            writer.close();
try-with-resources позволяет освобождать ресурсы в автоматическом режиме, так что `writer.close();` избыточен

2024-11-12 07:11 UTC, Sharapov-Maksim commented on Task_1_3_1/src/test/java/ru/nsu/syspro/zagitov/find/TestFindSubstring.java
> +public class TestFindSubstring {
Стоит добавить несколько тестов на краевые случаи: пустой файл, `|data| < |substring|`, пересекающиеся подстроки в файле

2024-11-12 07:11 UTC, Sharapov-Maksim commented on Task_1_3_1/src/test/java/ru/nsu/syspro/zagitov/find/TestFindSubstring.java
> +    public void testBigFile() throws IOException {
Попробуйте провести эксперимент: запустить данный тест с ограниченным размером кучи (см. -Xmx VM option, например: `-Xmx256m`. Или `maxHeapSize = '256m'` в `build.gradle`), проверить, что он не падает с OutOfMemory

2024-11-12 07:11 UTC, Sharapov-Maksim commented on Task_1_3_1/src/test/java/ru/nsu/syspro/zagitov/find/TestFindSubstring.java
> +            assert Objects.equals(res, List.of(3L, 14L));
Такие `assert`'ы не относятся к JUnit и работают только при выставлении VM option `-ea`. Давайте заменим на `Assertions.assertEquals(...)`

2024-11-12 07:15 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_3_1/src/test/java/ru/nsu/syspro/zagitov/find/TestFindSubstring.java
> +            writer.close();
я ж в try блоке позже обращаюсь к файлу(считываю с него), и если после записи(после двух for-ов) файл не закрыть, то при чтении в файле будет пусто

2024-11-12 07:18 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_3_1/src/test/java/ru/nsu/syspro/zagitov/find/TestFindSubstring.java
> +public class TestFindSubstring {
пересекающие подстроки уже есть в тестах(тест `testFind1`)
остальное сделаю)

2024-11-12 11:39 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_3_1/src/test/java/ru/nsu/syspro/zagitov/find/TestFindSubstring.java
> +    public void testBigFile() throws IOException {
проверил, всё работает)

2024-11-12 11:40 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_3_1/src/test/java/ru/nsu/syspro/zagitov/find/TestFindSubstring.java
> +            assert Objects.equals(res, List.of(3L, 14L));
сделал

2024-11-12 11:40 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_3_1/src/test/java/ru/nsu/syspro/zagitov/find/TestFindSubstring.java
> +public class TestFindSubstring {
сделал

2024-11-12 11:40 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_3_1/src/main/java/ru/nsu/syspro/zagitov/find/Main.java
> +}
сделал

2024-11-13 06:33 UTC, Sharapov-Maksim approved these changes
Задание зачтено, PR можно мёржить

2024-11-13 08:23 UTC, merged