Task_1_2_2
RostyanYandexLyceumCheeeeck/OOP pull request #6
Opened 2024-12-10 10:07 UTC by RostyanYandexLyceumCheeeeck

WoW

2024-12-10 10:09 UTC, RostyanYandexLyceumCheeeeck commented
review please)

2024-12-10 16:06 UTC, Sharapov-Maksim requested changes

2024-12-10 16:06 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/ru/nsu/syspro/zagitov/hashtable/HashTable.java
> +            if (other.get(entry.key) != entry.value) {
Значения нужно на `equals` проверять, а не на идентичность

2024-12-10 16:06 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/ru/nsu/syspro/zagitov/hashtable/HashTable.java
> +            if (other.get(entry.key) != entry.value) {
Опишите, как вы понимаете разницу между `Object.equals` и `==`?

2024-12-10 16:06 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/ru/nsu/syspro/zagitov/hashtable/HashTable.java
> +        private final int frozenSize = size;
`frozenSize` не до конца описывает точное состояние таблицы:
```
var m = new HashMap();
m.put("a", 0);
var i = m.iterator();
m.put("a", 1);
i.hasNext();
```

Можно завести счётчик, который бы инкрементировался на каждой модификации таблицы, и запоминать его значение

2024-12-10 16:06 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/ru/nsu/syspro/zagitov/hashtable/HashTable.java
> +     *
не хватает описания

2024-12-10 16:06 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/ru/nsu/syspro/zagitov/hashtable/HashTable.java
> +        private final int frozenSize = size;
И тест сделайте, который такое ловит

2024-12-10 17:16 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_2_2/src/main/java/ru/nsu/syspro/zagitov/hashtable/HashTable.java
> +            if (other.get(entry.key) != entry.value) {
Ну, если имеется ввиду именно родительский класс `Object`, то разницы между `Object.equals` и `==` нет. а если говорить в общем случае, то обычно метод `equals` переопределяют так, чтобы он сравнивал значения, а `==` -- ссылки на обьекты.

2024-12-10 17:19 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_2_2/src/main/java/ru/nsu/syspro/zagitov/hashtable/HashTable.java
> +     *
fixed

2024-12-10 17:20 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_2_2/src/main/java/ru/nsu/syspro/zagitov/hashtable/HashTable.java
> +        private final int frozenSize = size;
fixed

2024-12-10 17:20 UTC, RostyanYandexLyceumCheeeeck commented on Task_1_2_2/src/main/java/ru/nsu/syspro/zagitov/hashtable/HashTable.java
> +            if (other.get(entry.key) != entry.value) {
fix

2024-12-13 15:44 UTC, Sharapov-Maksim approved these changes
Задание зачтено

2024-12-13 15:44 UTC, Sharapov-Maksim commented on Task_1_2_2/src/main/java/ru/nsu/syspro/zagitov/hashtable/HashTable.java
> +                countOperations += (entry.value.equals(value) && entry.value == value) ? 0 : 1;
Тут было бы достаточно только второй части условия `entry.value == value`, потому что из `entry.value == value` следует что `entry.value.equals(value)`

2025-02-03 04:16 UTC, merged